# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import eos_pb2 as eos__pb2


class EOSStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreateShare = channel.unary_unary(
        '/EOS/CreateShare',
        request_serializer=eos__pb2.CreateShareRequest.SerializeToString,
        response_deserializer=eos__pb2.Response.FromString,
        )


class EOSServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def CreateShare(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_EOSServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CreateShare': grpc.unary_unary_rpc_method_handler(
          servicer.CreateShare,
          request_deserializer=eos__pb2.CreateShareRequest.FromString,
          response_serializer=eos__pb2.Response.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'EOS', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
