# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eos.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='eos.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\teos.proto\"\"\n\x12\x43reateShareRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\".\n\x08Response\x12\x0b\n\x03msg\x18\x01 \x01(\t\x12\x15\n\rresponse_code\x18\x02 \x01(\x05\x32\x36\n\x03\x45OS\x12/\n\x0b\x43reateShare\x12\x13.CreateShareRequest\x1a\t.Response\"\x00\x62\x06proto3')
)




_CREATESHAREREQUEST = _descriptor.Descriptor(
  name='CreateShareRequest',
  full_name='CreateShareRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='CreateShareRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=13,
  serialized_end=47,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='Response.msg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='response_code', full_name='Response.response_code', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=95,
)

DESCRIPTOR.message_types_by_name['CreateShareRequest'] = _CREATESHAREREQUEST
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CreateShareRequest = _reflection.GeneratedProtocolMessageType('CreateShareRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATESHAREREQUEST,
  '__module__' : 'eos_pb2'
  # @@protoc_insertion_point(class_scope:CreateShareRequest)
  })
_sym_db.RegisterMessage(CreateShareRequest)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'eos_pb2'
  # @@protoc_insertion_point(class_scope:Response)
  })
_sym_db.RegisterMessage(Response)



_EOS = _descriptor.ServiceDescriptor(
  name='EOS',
  full_name='EOS',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=97,
  serialized_end=151,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateShare',
    full_name='EOS.CreateShare',
    index=0,
    containing_service=None,
    input_type=_CREATESHAREREQUEST,
    output_type=_RESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_EOS)

DESCRIPTOR.services_by_name['EOS'] = _EOS

# @@protoc_insertion_point(module_scope)
