# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import eos_pb2 as eos__pb2


class EosStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ServerRequest = channel.unary_unary(
        '/Eos/ServerRequest',
        request_serializer=eos__pb2.ManilaRequest.SerializeToString,
        response_deserializer=eos__pb2.ManilaResponse.FromString,
        )


class EosServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ServerRequest(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_EosServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ServerRequest': grpc.unary_unary_rpc_method_handler(
          servicer.ServerRequest,
          request_deserializer=eos__pb2.ManilaRequest.FromString,
          response_serializer=eos__pb2.ManilaResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Eos', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
