# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eos.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='eos.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\teos.proto\"\xa4\x02\n\rManilaRequest\x12*\n\x0crequest_type\x18\x01 \x01(\x0e\x32\x14.MANILA_REQUEST_TYPE\x12\x10\n\x08\x61uth_key\x18\x02 \x01(\t\x12\x10\n\x08protocol\x18\x03 \x01(\t\x12\x12\n\nshare_name\x18\x04 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x05 \x01(\t\x12\x10\n\x08share_id\x18\x06 \x01(\t\x12\x16\n\x0eshare_group_id\x18\x07 \x01(\t\x12\r\n\x05quota\x18\x08 \x01(\x03\x12\x0f\n\x07\x63reator\x18\t \x01(\t\x12\x0e\n\x06\x65group\x18\n \x01(\t\x12\x14\n\x0c\x61\x64min_egroup\x18\x0b \x01(\t\x12\x12\n\nshare_host\x18\x0c \x01(\t\x12\x16\n\x0eshare_location\x18\r \x01(\t\"\x88\x01\n\x0eManilaResponse\x12\x0b\n\x03msg\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x02 \x01(\x05\x12\x12\n\ntotal_used\x18\x03 \x01(\x03\x12\x16\n\x0etotal_capacity\x18\x04 \x01(\x03\x12\x17\n\x0fnew_share_quota\x18\x05 \x01(\x03\x12\x16\n\x0enew_share_path\x18\x06 \x01(\t*\x94\x01\n\x13MANILA_REQUEST_TYPE\x12\x10\n\x0c\x43REATE_SHARE\x10\x00\x12\x10\n\x0c\x44\x45LETE_SHARE\x10\x01\x12\x10\n\x0c\x45XTEND_SHARE\x10\x02\x12\x10\n\x0cSHRINK_SHARE\x10\x03\x12\x13\n\x0fMANAGE_EXISTING\x10\x04\x12\x0c\n\x08UNMANAGE\x10\x05\x12\x12\n\x0eGET_CAPACITIES\x10\x06\x32?\n\x03\x45os\x12\x38\n\x13ManilaServerRequest\x12\x0e.ManilaRequest\x1a\x0f.ManilaResponse\"\x00\x62\x06proto3')
)

_MANILA_REQUEST_TYPE = _descriptor.EnumDescriptor(
  name='MANILA_REQUEST_TYPE',
  full_name='MANILA_REQUEST_TYPE',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CREATE_SHARE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DELETE_SHARE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EXTEND_SHARE', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SHRINK_SHARE', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MANAGE_EXISTING', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNMANAGE', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GET_CAPACITIES', index=6, number=6,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=448,
  serialized_end=596,
)
_sym_db.RegisterEnumDescriptor(_MANILA_REQUEST_TYPE)

MANILA_REQUEST_TYPE = enum_type_wrapper.EnumTypeWrapper(_MANILA_REQUEST_TYPE)
CREATE_SHARE = 0
DELETE_SHARE = 1
EXTEND_SHARE = 2
SHRINK_SHARE = 3
MANAGE_EXISTING = 4
UNMANAGE = 5
GET_CAPACITIES = 6



_MANILAREQUEST = _descriptor.Descriptor(
  name='ManilaRequest',
  full_name='ManilaRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='request_type', full_name='ManilaRequest.request_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='auth_key', full_name='ManilaRequest.auth_key', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='protocol', full_name='ManilaRequest.protocol', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='share_name', full_name='ManilaRequest.share_name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='description', full_name='ManilaRequest.description', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='share_id', full_name='ManilaRequest.share_id', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='share_group_id', full_name='ManilaRequest.share_group_id', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='quota', full_name='ManilaRequest.quota', index=7,
      number=8, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='creator', full_name='ManilaRequest.creator', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='egroup', full_name='ManilaRequest.egroup', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='admin_egroup', full_name='ManilaRequest.admin_egroup', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='share_host', full_name='ManilaRequest.share_host', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='share_location', full_name='ManilaRequest.share_location', index=12,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=306,
)


_MANILARESPONSE = _descriptor.Descriptor(
  name='ManilaResponse',
  full_name='ManilaResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='ManilaResponse.msg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='code', full_name='ManilaResponse.code', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='total_used', full_name='ManilaResponse.total_used', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='total_capacity', full_name='ManilaResponse.total_capacity', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='new_share_quota', full_name='ManilaResponse.new_share_quota', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='new_share_path', full_name='ManilaResponse.new_share_path', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=309,
  serialized_end=445,
)

_MANILAREQUEST.fields_by_name['request_type'].enum_type = _MANILA_REQUEST_TYPE
DESCRIPTOR.message_types_by_name['ManilaRequest'] = _MANILAREQUEST
DESCRIPTOR.message_types_by_name['ManilaResponse'] = _MANILARESPONSE
DESCRIPTOR.enum_types_by_name['MANILA_REQUEST_TYPE'] = _MANILA_REQUEST_TYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ManilaRequest = _reflection.GeneratedProtocolMessageType('ManilaRequest', (_message.Message,), {
  'DESCRIPTOR' : _MANILAREQUEST,
  '__module__' : 'eos_pb2'
  # @@protoc_insertion_point(class_scope:ManilaRequest)
  })
_sym_db.RegisterMessage(ManilaRequest)

ManilaResponse = _reflection.GeneratedProtocolMessageType('ManilaResponse', (_message.Message,), {
  'DESCRIPTOR' : _MANILARESPONSE,
  '__module__' : 'eos_pb2'
  # @@protoc_insertion_point(class_scope:ManilaResponse)
  })
_sym_db.RegisterMessage(ManilaResponse)



_EOS = _descriptor.ServiceDescriptor(
  name='Eos',
  full_name='Eos',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=598,
  serialized_end=661,
  methods=[
  _descriptor.MethodDescriptor(
    name='ManilaServerRequest',
    full_name='Eos.ManilaServerRequest',
    index=0,
    containing_service=None,
    input_type=_MANILAREQUEST,
    output_type=_MANILARESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_EOS)

DESCRIPTOR.services_by_name['Eos'] = _EOS

# @@protoc_insertion_point(module_scope)
